# Generated by Django 5.0.7 on 2024-07-20 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("transaction", "0003_alter_transaction_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_source",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_source_name",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_sub_method",
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_source_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_source_type",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="contenttypes.contenttype"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_method",
            field=models.CharField(
                choices=[("bank", "Bank"), ("credit_card", "Credit Card"), ("debit_card", "Debit Card"), ("wallet", "Wallet"), ("upi", "UPI")],
                max_length=20,
            ),
        ),
    ]
