# Generated by Django 5.0.7 on 2024-07-24 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0006_transaction_created_at_transaction_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_mode",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
