# Generated by Django 5.0.7 on 2024-11-14 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("product", "0001_initial"),
        ("type", "0001_initial"),
        ("variant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"], "verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="category.productcategory", verbose_name="Category"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=200, verbose_name="Product Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="type.producttype", verbose_name="Product Type"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=20, unique=True, verbose_name="SKU"),
        ),
        migrations.AlterField(
            model_name="product",
            name="variant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="variant.productvariant", verbose_name="Variant"),
        ),
    ]
