# Generated by Django 5.0.7 on 2024-07-31 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upi",
            name="app",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="upi_accounts", to="upi.upiapp"),
        ),
    ]
