# Stage 1: Build
FROM node:18-slim AS build

WORKDIR /srv/app
# COPY package.json package-lock.json ./
# RUN npm install
COPY . ./
# RUN npm run build

# Stage 2: Serve
FROM nginx:alpine

# Copy build artifacts
COPY --from=build /srv/app/dist /usr/share/nginx/html

# Copy custom nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
