# Generated by Django 5.0.7 on 2024-07-16 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoice_group", "0001_initial"),
        ("invoice_user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="invoices/")),
                ("description", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("invoice_date", models.DateTimeField()),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="invoice_group.category")),
                ("invoice_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="invoice_user.user")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("final_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="invoice.invoice")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoice_items", to="invoice_group.option")),
            ],
        ),
    ]
