# Generated by Django 5.0.7 on 2024-07-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="title",
            field=models.CharField(default="test1", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="description",
            field=models.CharField(),
        ),
    ]
