# Generated by Django 5.0.7 on 2024-07-16 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bank_account", "0003_alter_bankaccount_account_type_alter_bankaccount_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebitCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_type", models.CharField(choices=[("master", "Master"), ("visa", "Visa"), ("rupay", "Rupay")], max_length=10)),
                ("card_number", models.CharField(max_length=16, unique=True)),
                ("expiry_date", models.DateField()),
                ("cvv", models.CharField(max_length=3)),
                ("holder_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="account_debit", to="bank_account.bankaccount"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
