# Generated by Django 5.0.7 on 2024-07-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_card", "0002_creditcard_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
