# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy custom Nginx configuration file into the container
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static and media volumes into the container
VOLUME ["/srv/app/static", "/srv/app/media"]

# Expose port 80
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
