# Generated by Django 5.0.7 on 2024-11-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_billingitem_total_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingitem",
            options={},
        ),
    ]
