# Generated by Django 5.0.7 on 2024-11-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_billingitem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingitem",
            options={"verbose_name": "Billing Item", "verbose_name_plural": "Billing Items"},
        ),
    ]
