# Generated by Django 5.0.7 on 2024-11-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_billing_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="billing_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
