# Generated by Django 5.0.7 on 2024-11-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_billing_billing_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Discount applied to the bill", max_digits=10),
        ),
    ]
