# Generated by Django 5.0.7 on 2024-11-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_billing_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Not editable from admin auto calculation will happen", max_digits=10),
        ),
    ]
