name: Deploy Application

on:
  push:
    branches:
      - main # Change this to your default branch if it's not `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install SSH Client
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      # Create .ssh directory
      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      # # Add SSH Host Key to known hosts (uncomment if needed)
      # - name: Add SSH Host Key
      #   run: |
      #     ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      # Deploy to DigitalOcean
      - name: Deploy to DigitalOcean
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }} # Ensure this secret is added in GitHub Secrets
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} -p 5417 << 'EOF'
            set -e  # Exit on any error
            if [ -d /mnt/dev/finfolio ]; then
              cd /mnt/dev/finfolio
              if [ -d .git ]; then
                git pull origin main  # Update your codebase if it's a Git repository
                docker-compose -f docker-compose.prod.yml down
                docker-compose -f docker-compose.prod.yml pull
                docker-compose -f docker-compose.prod.yml build
                docker-compose -f docker-compose.prod.yml up -d
              else
                echo "Not a git repository, skipping git pull"
              fi
            else
              echo "Directory /mnt/dev/finfolio does not exist"
              exit 1
            fi
          EOF
