name: Deploy Application

on:
  push:
    branches:
      - main # Change this to your default branch if it's not `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install SSH Client and sshpass
      - name: Install SSH Client and sshpass
        run: sudo apt-get install -y openssh-client sshpass

      # Create .ssh directory
      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      # Add SSH Host Key
      - name: Add SSH Host Key
        run: |
          echo "Setting up SSH and known_hosts"
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      # Deploy to DigitalOcean
      - name: Deploy to DigitalOcean
        env:
          SSH_PASSWORD: ${{ secrets.DO_SSH_PASSWORD }}
        run: |
          sshpass -p "${SSH_PASSWORD}" ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            set -e  # Exit on any error
            if [ -d /mnt/dev/finfolio ]; then
              cd /mnt/dev/finfolio
              if [ -d .git ]; then
                git pull origin main  # Update your codebase if it's a Git repository
                docker-compose -f docker-compose.prod.yml down
                docker-compose -f docker-compose.prod.yml pull
                docker-compose -f docker-compose.prod.yml build
                docker-compose -f docker-compose.prod.yml up -d
              else
                echo "Not a git repository, skipping git pull"
              fi
            else
              echo "Directory /mnt/dev/finfolio does not exist"
              exit 1
            fi
          EOF
