name: Deploy Application

on:
  push:
    branches:
      - main # Change this to your default branch if it's not `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker-compose build

      - name: Install SSH Client and sshpass
        run: sudo apt-get install -y openssh-client sshpass

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Add SSH Host Key
        run: |
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        env:
          SSH_PASSWORD: ${{ secrets.DO_SSH_PASSWORD }}
        run: |
          sshpass -p "${SSH_PASSWORD}" ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            if [ -d /mnt/dev/portfolio ]; then
              cd /mnt/dev/portfolio
              if [ -d .git ]; then
                git pull origin main || exit 1  # Update your codebase if it's a Git repository
              else
                echo "Not a git repository, skipping git pull"
              fi
              if [ -f docker-compose.yml ] || [ -f docker-compose.yaml ]; then
                docker-compose pull || exit 1
                docker-compose up -d || exit 1
              else
                echo "docker-compose.yml file not found, skipping Docker commands"
                exit 1
              fi
            else
              echo "Directory /mnt/dev/portfolio does not exist"
              exit 1
            fi
          EOF
