name: Deploy Application

on:
  push:
    branches:
      - main # Change this to your default branch if it's not `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Build Docker images
      #   run: docker-compose build

      - name: Install SSH Client and sshpass
        run: sudo apt-get install -y openssh-client sshpass

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Add SSH Host Key
        run: |
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        env:
          SSH_PASSWORD: ${{ secrets.DO_SSH_PASSWORD }}
        run: |
          sshpass -p "${SSH_PASSWORD}" ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            set -e  # Exit on any error
            if [ -d /mnt/dev/finfolio ]; then
              cd /mnt/dev/finfolio
              if [ -d .git ]; then
                git pull origin main  # Update your codebase if it's a Git repository
              else
                echo "Not a git repository, skipping git pull"
              fi
              if [ -f  docker-compose -f docker-compose.prod.yml.yml ] || [ -f  docker-compose -f docker-compose.prod.yml.yaml ]; then
                # Check Docker and Docker Compose installation
                docker --version || (echo "Docker is not installed" && exit 1)
                 docker-compose -f docker-compose.prod.yml --version || (echo "Docker Compose is not installed" && exit 1)
                 docker-compose -f docker-compose.prod.yml down
                 docker-compose -f docker-compose.prod.yml pull
                 docker-compose -f docker-compose.prod.yml build
                 docker-compose -f docker-compose.prod.yml up -d
              else
                echo " docker-compose -f docker-compose.prod.yml.yml file not found, skipping Docker commands"
                exit 1
              fi
            else
              echo "Directory /mnt/dev/finfolio does not exist"
              exit 1
            fi
          EOF
