name: Deploy Application

on:
  push:
    branches:
      - main # Change this to your default branch if it's not `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker-compose build

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH Host Key
        run: |
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        env:
          SSH_PASSWORD: ${{ secrets.DO_SSH_PASSWORD }}
        run: |
          sshpass -p "${SSH_PASSWORD}" ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            cd /path/to/your/application  # Change this to the path on your droplet
            git pull origin main  # Optional: Update your codebase
            docker-compose pull
            docker-compose up -d
          EOF
