name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: SSH to server and run Docker commands
        run: |
          sshpass -p ${{ secrets.DO_SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.DO_PORT }} ${{
            secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            git pull origin main  # Update your codebase
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml build
            docker-compose -f docker-compose.prod.yml up -d
          EOF
